---
repos:
- repo: 'https://github.com/pre-commit/pre-commit-hooks'
  rev: v5.0.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: 'https://github.com/adrienverge/yamllint'
  rev: v1.35.1
  hooks:
  - id: yamllint
    files: \.yaml(fmt|lint)?$
- repo: 'https://github.com/google/yamlfmt'
  rev: v0.13.0
  hooks:
  - id: yamlfmt
    files: \.yaml(fmt|lint)?$
- repo: 'https://github.com/executablebooks/mdformat'
  rev: 0.7.18
  hooks:
  - id: mdformat
- repo: 'https://github.com/scop/pre-commit-shfmt'
  rev: v3.10.0-1
  hooks:
  - id: shfmt
- repo: local
  hooks:
  - id: patchversion
    name: LIBSH_VERSION
    entry: .pre-commit-patch-version
    language: script
    types:
    - bash
    pass_filenames: false
    always_run: true
